# action.yml
name: "GPG key import"
description: "Import private GPG key"
runs:
  using: "composite"
  steps:
    - run: |
        #
        echo -e "${{ env.GPG_PRIVATE_KEY }}" | gpg --import --batch --no-tty
        echo "hello world" > temp.txt
        gpg --detach-sig --yes -v --output=/dev/null --pinentry-mode loopback --passphrase "${{ env.PASSPHRASE }}" temp.txt
        rm temp.txt
      shell: bash
      name: import GPG key and prime passphrase
    - id: gpg-fingerprint
      run: |
        fingerprint=$(gpg --with-colons --list-keys | awk -F: '/^pub/ { print $5 }')
        echo "::set-output name=fingerprint::$fingerprint"
      shell: bash
      name: set gpg key fingerprint
    - id: gpg-pubkey
      run: |
        pubkey=$(gpg --export --armor ${{ steps.gpg-fingerprint.outputs.fingerprint }} | sed 's/$/\\\\n/' | tr -d '\n')
        echo "::set-output name=pubkey::$pubkey"
      shell: bash
      name: set gpg key pubkey

outputs:
  fingerprint:
    description: "Fingerprint of the GPG key"
    value: ${{ steps.gpg-fingerprint.outputs.fingerprint }}
  pubkey:
    description: "Base64 encoded, armored pubkey of the GPG key"
    value: ${{ steps.gpg-pubkey.outputs.pubkey }}

