# action.yml
name: "GPG key import"
description: "Import private GPG key"
runs:
  using: "composite"
  steps:
    - run: |
        #
        echo -e "${{ env.GPG_PRIVATE_KEY }}" | gpg --import --batch --no-tty
        echo "hello world" > temp.txt
        gpg --detach-sig --yes -v --output=/dev/null --pinentry-mode loopback --passphrase "${{ env.PASSPHRASE }}" temp.txt
        rm temp.txt
      shell: bash
      name: import GPG key and prime passphrase
